### ISSUE TITLE
"Were sorry but something went wrong"

### ISSUE THREAD

**Issue by Andeebee** [ualbertalib/NEOSDiscovery#106]

**Comment by Andeebee** [comment]
Receiving error - "Were sorry but something went wrong. If you are the application owner check the logs for more information" when attempting to SMS, Email, Send a Correction (though some do go through ok).

**Comment by redlibrarian** [comment]
I've fixed this in dev, I hope to have this pushed into production this morning.

**Comment by Andeebee** [comment]
Retested SMS this morning - still not coming through for me.

**Comment by redlibrarian** [comment]
Weird. The SMS email message is going out successfully, as far as I can tell. Not sure where the problem is. I'll keep digging.

**Comment by redlibrarian** [comment]
Created separate issue #132 for the SMS problem.
