### ISSUE TITLE
"Incomplete response received from application" error

### ISSUE THREAD

**Issue by paulpype-goa** [ualbertalib/NEOSDiscovery#78]
When clicking on certain titles in search results, I get a page displaying an "Incomplete response received from application" error instead of the record. Here are some examples:
- https://barking.library.ualberta.ca/catalog/7065936 should go to record for _Multiple intelligences: new horizons, Completely rev. and updated_
- https://barking.library.ualberta.ca/catalog/7739740 should go to record for _Python geospatial development: build a complete and sophisticated mapping application from scratch using Python tools for GIS development_
- https://barking.library.ualberta.ca/catalog/3594135 should to to record for _Multiple intelligences: other styles of learning_

I've reproduced the problem in both Chrome and Firefox. The problem doesn't seem to be that widespread, but it's common enough that I was able to find these examples in a few minutes.

**Comment by kzarft** [comment]
I see the problem as well.  Search for nursing mentorship and quite a few titles on the first page of results are showing the problem.

**Comment by redlibrarian** [comment]
OK, this one should also be fixed now. Norquest was one of the problem mappings, so all Norquest records *should* be fixed. Please let me know if you find any more like this.

**Comment by paulpype-goa** [comment]
Unfortunately, I have a record that is not fixed: https://barking.library.ualberta.ca/catalog/6849207

**Comment by kzarft** [comment]
It looks like the NorQuest items are fixed. Could you change the spelling of Norquest to NorQuest?

**Comment by Andeebee** [comment]
I am also still seeing the error pop up on select items.

Examples: 
https://barking.library.ualberta.ca/catalog/5081005
https://barking.library.ualberta.ca/catalog/5987883
https://barking.library.ualberta.ca/catalog/4779240

**Comment by kzarft** [comment]
Looks like I was wrong.  There still seems to be an issue for us on this record https://barking.library.ualberta.ca/catalog/4875111

**Comment by redlibrarian** [comment]
OK, the NEOS Free resources are fixed - will be visible on barking when I push the next release.

**Comment by redlibrarian** [comment]
I've fixed the case of "NorQuest".

**Comment by redlibrarian** [comment]
OK, I've fixed all these examples. I'll let you know when I've pushed the new release to barking, at which time we'll need to double check that these have been fixed. If you notice any other problem records, please add them to this ticket.

**Comment by redlibrarian** [comment]
I'm going to provisionally close this as no new instances have been reported. We can reopen if necessary.
